<?php ob_start(); ?>
<?php
require_once('includes/db.php');
require_once('includes/functions.php');
require_once('includes/session.php');
require_once('includes/header.php');
require_once('includes/sidebar.php');

confirmLogin();
$_SESSION['TrackingURL'] = $_SERVER['PHP_SELF'];
?>

<?php

if(isset($_POST['Submit'])){
if(!empty($_POST['PostTitle']) ){
   $PostTitle = $_POST['PostTitle'];
   $Category = $_POST['Category'];
   $Content = $_POST['Content'];
   $AuthorName = $_SESSION['Aname'];
   $Image = $_FILES['Image']['name'];
   $Target = "uploads/".basename($_FILES['Image']['name']);
   $DateTime = datentime();
   if (empty($PostTitle)) {
       $_SESSION['errorMessage'] = "Post Title cannot be empty";
       Redirect_to('addnewpost.php');
   }
   elseif (empty($Content)) {
    $_SESSION['errorMessage'] = "Content cannot be empty";
    Redirect_to('addnewpost.php');
   }
   elseif (empty($Image)) {
    $_SESSION['errorMessage'] = "You have to Upload an image";
    Redirect_to('addnewpost.php');
   }
    elseif (strlen($Content)<50) {
    $_SESSION['errorMessage'] = "Content should be greater than 50 characters";
    Redirect_to('addnewpost.php');
   }
 else{
    // query to insert the data in to the database when everything is okay
    $dbconnection;
    $sql = "INSERT INTO posts (title,datetime,category,author,image,content)";
    $sql.= "VALUES(:tiTle, :datetIme, :cateGory, :autHor, :imaGe, :conTent)";
    $stmt = $dbconnection->prepare($sql);
    $stmt->bindValue(':tiTle', $PostTitle);
    $stmt->bindValue(':datetIme', $DateTime);
    $stmt->bindValue(':cateGory', $Category);
    $stmt->bindValue(':imaGe',  $Image);
    $stmt->bindValue(':conTent', $Content);
    $stmt->bindValue(':autHor', $AuthorName);
    $Execute= $stmt->execute();
    ////GET the inserted ID
    $autoGeneratedID = $dbconnection->lastInsertId();
    ///use the inserted to fill the newsCounter Table and set count=0
    $sqlCount = "INSERT INTO clicks (post_id,count) VALUES('$autoGeneratedID', '0' )";
    $stmt = $dbconnection->query($sqlCount);
    ///insert into table[clickCounter](news_id,count) values('$autoGeneratedID','0')
    move_uploaded_file($_FILES['Image']['tmp_name'], $Target);
    if($Execute){
        $_SESSION['successMessage']= "Post uploaded successfully";
        Redirect_to('addnewpost.php');
    }else{
        $_SESSION['errorMessage']= "Something went wrong try again";
        Redirect_to('addnewpost.php');
    }
} 
}
}
?>

<body class="header-fixed skin-blue">

    <!-- Header Section -->
    <header>

        <!-- Product Logo -->
        <a href="javascript:void(0);" class="logo hidden-xs">
            <span class="icon">
                <i class="fa fa-cube"></i>
            </span>
            Curo
        </a>
        <!-- End Product Logo -->

        <!-- Header Navigation -->
        <nav class="navbar-main" role="navigation">

            <!-- Left Button Container -->
            <ul class="button-container pull-left">

                <li class="item">
                    <!-- Left Sidebar Toggle Button -->
                    <a id="sidebarLeftToggle" class="nav-button" data-toggle="collapse" data-target=".sidebarLeft">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="fa fa-bars"></span>
                    </a>
                </li>

            </ul>
            <!-- End Left Button Container -->

            <!-- Navbar Content Center -->
            <div class="nav-content">
                <!-- Page Title -->
                <h3 class="page-title">Add New Post</h3>
                <!-- End Page Title -->
            </div>
            <!-- End Navbar Content Center -->

        </nav>
        <!-- End Header Navigation -->

    </header>
    <!-- End Header Section -->

    <!-- Page Content Wrapper -->
    <aside class="content-wrapper collapse sidebarLeft">

        <!-- Page Content -->
        <div class="content container-fluid sidebarRight animated fadeInUp mail message-list-wrapper">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-white">
                        <div class="panel-heading">
                            <h3 class="panel-title">Add Post</h3>
                        </div>
                        <div class="panel-body">
                            <?php
                  echo errorMessage();
                  echo successMessage();
                  ?>
                            <form enctype="multipart/form-data" action="addnewpost.php" method="post">
                                <div class="form-group">
                                    <label for="PostTitle">Post Title</label>
                                    <input type="text" class="form-control" id="" name="PostTitle"
                                        placeholder="Enter Title">
                                </div>
                                <div class="form-group">

                                    <label for="Category">Category</label>
                                    <select class="form-control mg-btm-10" name="Category">
                                        <?php
                                $dbconnection;
                                $sql = "SELECT * FROM categories";
                                $stmt=$dbconnection->query($sql);
                                while($DataRows=$stmt->fetch()){
                                    $CategoryName = $DataRows['CName'];

                            ?>
                                        <option><?php echo $CategoryName; ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="Image Upload">Select Image</label>
                                    <div class="fallback">
                                        <input name="Image" type="file" multiple />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="Content">Content</label>
                                    <textarea name="Content" id="editor" cols="80" rows="8"
                                        class="form-control ckeditor"></textarea>
                                </div>
                                <button type="submit" id="addNewPost" name="Submit"
                                    class="btn btn-default">Submit</button>

                            </form>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </aside>
    <script>
        ClassicEditor
    .create( document.querySelector( '#editor' ) )
    .then( editor => {
        console.log( editor );
    } )
    .catch( error => {
        console.error( error );
    } );
    </script>
    <?php require_once('includes/footer.php') ?>
    <?php ob_flush(); ?>